
import { Car, Testimonial } from './types';

// Helper to generate 9 generic but high-quality car-part related images for the 8-10 view requirement
const getMoreImages = (seed: string) => [
  `https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=600&sig=${seed}1`,
  `https://images.unsplash.com/photo-1568844293986-8d0400bd4745?auto=format&fit=crop&q=80&w=600&sig=${seed}2`,
  `https://images.unsplash.com/photo-1542362567-b051c63b5627?auto=format&fit=crop&q=80&w=600&sig=${seed}3`,
  `https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=600&sig=${seed}4`,
  `https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&q=80&w=600&sig=${seed}5`,
  `https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&q=80&w=600&sig=${seed}6`,
  `https://images.unsplash.com/photo-1494905998402-395d579af36f?auto=format&fit=crop&q=80&w=600&sig=${seed}7`,
  `https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&q=80&w=600&sig=${seed}8`,
  `https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=600&sig=${seed}9`,
];

export const CAR_DATA: Car[] = [
  {
    id: 'lexus-rx-2023',
    name: 'Lexus RX 350 2023 Gray',
    price: 75000000,
    year: 2023,
    make: 'Lexus',
    model: 'RX 350',
    condition: 'Foreign Used',
    mileage: '7,700 km',
    fuel: 'Petrol',
    transmission: 'Automatic',
    color: 'Gray',
    location: 'Alimosho, Lagos',
    description: 'The cleanest accident free 2023 Lexus Rx350 Full Option UNTOUCHED with no naija paint on the body. Digital dashboard, lane assist, premium sound.',
    imageUrl: '/cars/lexus-rx-2023/M10.jpg',
    additionalImages: [
      '/cars/lexus-rx-2023/M1.jpg',
      '/cars/lexus-rx-2023/M3.jpg',
      '/cars/lexus-rx-2023/M5.jpg',
      '/cars/lexus-rx-2023/M9.jpg',
      '/cars/lexus-rx-2023/M11.jpg',
      '/cars/lexus-rx-2023/M12.jpg',
      '/cars/lexus-rx-2023/M14.jpg'
    ],
    tags: ['Premium', 'SUV', 'Luxury'],
    features: ['Panoramic Roof', 'Digital Dashboard', 'Lane Assist', 'Adaptive Cruise', 'Heated Seats', 'Ventilated Seats', 'Premium Audio'],
    engine: '2.4L Turbo 4-cyl',
    bodyType: 'SUV'
  },
  {
    id: 'highlander-2016',
    name: 'Toyota Highlander XLE V6 4x4 2016 Burgundy',
    price: 30000000,
    year: 2016,
    make: 'Toyota',
    model: 'Highlander',
    trim: 'XLE V6 4x4',
    condition: 'Foreign Used',
    mileage: '139,000 km',
    fuel: 'Petrol',
    transmission: 'Automatic',
    color: 'Burgundy',
    location: 'Ikeja, Lagos',
    description: 'The cleanest accident free 2016 Toyota Highlander XLE edition UNTOUCHED with no naija paint on the body. Thumbstart ignition, leather seats.',
    imageUrl: '/cars/highlander-2016/1.jpg',
    additionalImages: [
      '/cars/highlander-2016/2.jpg',
      '/cars/highlander-2016/3.jpg',
      '/cars/highlander-2016/4.jpg',
      '/cars/highlander-2016/5.jpg',
      '/cars/highlander-2016/6.jpg',
      '/cars/highlander-2016/7.jpg',
      '/cars/highlander-2016/8.png'
    ],
    tags: ['SUV', 'AWD', 'Family'],
    features: ['Thumbstart', 'Leather Seats', 'Sunroof', 'Reverse Camera', 'AWD'],
    engine: '3.5L V6',
    bodyType: 'SUV'
  },
  {
    id: 'rav4-2013',
    name: 'Toyota RAV4 Limited AWD 2013 Silver',
    price: 22000000,
    year: 2013,
    make: 'Toyota',
    model: 'RAV4',
    condition: 'Foreign Used',
    mileage: '174,695 km',
    fuel: 'Petrol',
    transmission: 'Automatic',
    color: 'Silver',
    location: 'Agege, Lagos',
    description: 'Tokunbo Toyota RAV4 2013 model Limited With Thumbstart ignition, Leather seat, power booth.',
    imageUrl: '/cars/rav4-2013/R2.jpg',
    additionalImages: [
      '/cars/rav4-2013/R1.jpg',
      '/cars/rav4-2013/R3.jpg',
      '/cars/rav4-2013/R4.jpg',
      '/cars/rav4-2013/R5.jpg',
      '/cars/rav4-2013/R6.jpg',
      '/cars/rav4-2013/R7.jpg',
      '/cars/rav4-2013/R8.jpg'
    ],
    tags: ['SUV', 'AWD', 'Limited'],
    features: ['Power Boot', 'Thumbstart', 'Leather Seats', 'Limited Edition'],
    engine: '2.5L 4-cylinder',
    bodyType: 'SUV'
  },
  {
    id: 'venza-2014',
    name: 'Toyota Venza XLE 4dr Wagon AWD 2014 Gray',
    price: 21000000,
    year: 2014,
    make: 'Toyota',
    model: 'Venza',
    condition: 'Foreign Used',
    mileage: '198,570 km',
    fuel: 'Petrol',
    transmission: 'Automatic',
    color: 'Gray',
    location: 'Agege, Lagos',
    description: 'Tokunbo 2014 Toyota Venza XLE With 4plug engine, panoramic roof, leather seat, Keystart.',
    imageUrl: '/cars/venza-2014/1.jpg',
    additionalImages: [
      '/cars/venza-2014/2.jpg',
      '/cars/venza-2014/3.jpg',
      '/cars/venza-2014/4.jpg',
      '/cars/venza-2014/5.jpg',
      '/cars/venza-2014/6.jpg',
      '/cars/venza-2014/7.jpg',
      '/cars/venza-2014/8.jpg',
      '/cars/venza-2014/9.jpg',
      '/cars/venza-2014/10.jpg',
      '/cars/venza-2014/11.jpg',
      '/cars/venza-2014/12.jpg'
    ],
    tags: ['Panoramic', 'XLE', 'Luxury'],
    features: ['Panoramic Roof', 'Leather Seats', 'AWD', 'Bluetooth'],
    engine: '2.7L 4-cylinder',
    bodyType: 'SUV'
  },
  {
    id: 'corolla-gray-2014',
    name: 'Toyota Corolla LE 4dr Sedan 2014 Gray',
    price: 13200000,
    year: 2014,
    make: 'Toyota',
    model: 'Corolla',
    condition: 'Foreign Used',
    mileage: '120,000 km',
    fuel: 'Petrol',
    transmission: 'Automatic',
    color: 'Gray',
    location: 'Ikeja, Lagos',
    description: 'Foreign Used Toyota Corolla LE 2014 model with very sound engine and gear.',
    imageUrl: '/cars/corolla-gray-2014/1.jpg',
    additionalImages: [
      '/cars/corolla-gray-2014/2.jpg',
      '/cars/corolla-gray-2014/3.jpg',
      '/cars/corolla-gray-2014/4.jpg',
      '/cars/corolla-gray-2014/5.jpg',
      '/cars/corolla-gray-2014/6.jpg',
      '/cars/corolla-gray-2014/7.jpg',
      '/cars/corolla-gray-2014/8.jpg',
      '/cars/corolla-gray-2014/9.jpg',
      '/cars/corolla-gray-2014/10.jpg'
    ],
    tags: ['Sedan', 'Economy', 'Reliable'],
    features: ['Backup Camera', 'Bluetooth', 'CVT Transmission'],
    engine: '1.8L 4-cylinder',
    bodyType: 'Sedan'
  },
  {
    id: 'sienna-2009',
    name: 'Toyota Sienna XLE Limited AWD 2009 Silver',
    price: 12500000,
    year: 2009,
    make: 'Toyota',
    model: 'Sienna',
    condition: 'Foreign Used',
    mileage: '185,000 km',
    fuel: 'Petrol',
    transmission: 'Automatic',
    color: 'Silver',
    location: 'Agege, Lagos',
    description: 'Accident free Toyota Sienna 2009 Model with two power doors and back DVD screen.',
    imageUrl: '/cars/sienna-2009/1.jpg',
    additionalImages: [
      '/cars/sienna-2009/2.jpg',
      '/cars/sienna-2009/3.jpg',
      '/cars/sienna-2009/4.jpg',
      '/cars/sienna-2009/5.jpg',
      '/cars/sienna-2009/6.jpg',
      '/cars/sienna-2009/7.jpg',
      '/cars/sienna-2009/8.jpg'
    ],
    tags: ['MiniVan', 'Family', 'DVD'],
    features: ['Two Power Doors', 'DVD Screen', 'Leather Interior'],
    engine: '3.5L V6',
    bodyType: 'MiniVan'
  },
  {
    id: 'ford-transit-2012',
    name: 'Ford Transit 2012 White',
    price: 11500000,
    year: 2012,
    make: 'Ford',
    model: 'Transit',
    condition: 'Foreign Used',
    mileage: '178,000 km',
    fuel: 'Petrol',
    transmission: 'Automatic',
    color: 'White',
    location: 'Ikeja, Lagos',
    description: 'Foreign used Ford Transit Connet 2012 Model with sound engine and gear.',
    imageUrl: '/cars/ford-transit-2012/1.png',
    additionalImages: [
      '/cars/ford-transit-2012/2.png',
      '/cars/ford-transit-2012/3.png',
      '/cars/ford-transit-2012/4.png',
      '/cars/ford-transit-2012/5.png',
      '/cars/ford-transit-2012/6.png',
      '/cars/ford-transit-2012/7.png',
      '/cars/ford-transit-2012/8.png'
    ],
    tags: ['Van', 'Commercial', 'Utility'],
    features: ['Solid Engine', 'Spacious Cargo', 'Reliable Utility'],
    engine: '2.0L 4-cylinder',
    bodyType: 'Van'
  },
  {
    id: 'corolla-white-2014',
    name: 'Toyota Corolla L 4dr Sedan 2014 White',
    price: 13000000,
    year: 2014,
    make: 'Toyota',
    model: 'Corolla',
    condition: 'Foreign Used',
    mileage: '98,000 km',
    fuel: 'Petrol',
    transmission: 'Automatic',
    color: 'White',
    location: 'Ikeja, Lagos',
    description: 'Clean Foreign used Toyota Corolla 2014 LE with very sharp engine and gear.',
    imageUrl: '/cars/corolla-white-2014/1.png',
    additionalImages: [
      '/cars/corolla-white-2014/2.png',
      '/cars/corolla-white-2014/3.png',
      '/cars/corolla-white-2014/4.png',
      '/cars/corolla-white-2014/5.png'
    ],
    tags: ['Sedan', 'White', 'Clean'],
    features: ['Eco Mode', 'Bluetooth', 'Daytime Running Lights'],
    engine: '1.8L 4-cylinder',
    bodyType: 'Sedan'
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    author: 'Emeka Nwosu',
    role: 'Business Owner',
    content: 'Testycare provided exceptional service. The Toyota Venza I bought was exactly as described. Clean, sound, and ready for the road.',
    avatar: 'https://i.pravatar.cc/150?u=emeka'
  },
  {
    id: '2',
    author: 'Sarah Ajayi',
    role: 'Corporate Professional',
    content: 'Found my dream Corolla here. The process was transparent and the team was very helpful with all my documentation.',
    avatar: 'https://i.pravatar.cc/150?u=sarah'
  },
  {
    id: '3',
    author: 'Oluwaseun Adeyemi',
    role: 'Logistics Manager',
    content: 'Bought a Ford Transit for our fleet. The engine is solid and the price was competitive. Highly recommended for business vehicles.',
    avatar: 'https://i.pravatar.cc/150?u=olu'
  }
];
